#!/usr/bin/env bash
[2;2R[>77;30700;0c]10;rgb:bfbf/bfbf/bfbf]11;rgb:0000/0000/0000# shellcheck disable=SC2086

args="$#"

if [[ "$args" -eq 1 ]]
then
	dig www."$1" | grep -A1 'ANSWER SECTION:' | tail -n +2 | awk '{printf "The subdomain www is a %s record and points to %s\n", $4, $5}'
	dig lb-01."$1" | grep -A1 'ANSWER SECTION:' | tail -n +2 | awk '{printf "The subdomain lb-01 is a %s record and points to %s\n", $4, $5}'
	dig web-01."$1" | grep -A1 'ANSWER SECTION:' | tail -n +2 | awk '{printf "The subdomain web-01 is a %s record and points to %s\n", $4, $5}'
	dig web-02."$1" | grep -A1 'ANSWER SECTION:' | tail -n +2 | awk '{printf "The subdomain web-02 is a %s record and points to %s\n", $4, $5}'
fi
